package ir.moonify.exchangeapp.util

object Constants {
    const val OFFLINE_RATES: String = "{\n" +
            "    \"success\": true,\n" +
            "    \"timestamp\": 1647328683,\n" +
            "    \"base\": \"EUR\",\n" +
            "    \"date\": \"2022-03-15\",\n" +
            "    \"rates\": [\n" +
            "    \"AED\",\n" +
            "    \"AFN\",\n" +
            "    \"ALL\",\n" +
            "    \"AMD\",\n" +
            "    \"ANG\",\n" +
            "    \"AOA\",\n" +
            "    \"ARS\",\n" +
            "    \"AUD\",\n" +
            "    \"AWG\",\n" +
            "    \"AZN\",\n" +
            "    \"BAM\",\n" +
            "    \"BBD\",\n" +
            "    \"BDT\",\n" +
            "    \"BGN\",\n" +
            "    \"BHD\",\n" +
            "    \"BIF\",\n" +
            "    \"BMD\",\n" +
            "    \"BND\",\n" +
            "    \"BOB\",\n" +
            "    \"BRL\",\n" +
            "    \"BSD\",\n" +
            "    \"BTC\",\n" +
            "    \"BTN\",\n" +
            "    \"BWP\",\n" +
            "    \"BYN\",\n" +
            "    \"BYR\",\n" +
            "    \"BZD\",\n" +
            "    \"CAD\",\n" +
            "    \"CDF\",\n" +
            "    \"CHF\",\n" +
            "    \"CLF\",\n" +
            "    \"CLP\",\n" +
            "    \"CNY\",\n" +
            "    \"COP\",\n" +
            "    \"CRC\",\n" +
            "    \"CUC\",\n" +
            "    \"CUP\",\n" +
            "    \"CVE\",\n" +
            "    \"CZK\",\n" +
            "    \"DJF\",\n" +
            "    \"DKK\",\n" +
            "    \"DOP\",\n" +
            "    \"DZD\",\n" +
            "    \"EGP\",\n" +
            "    \"ERN\",\n" +
            "    \"ETB\",\n" +
            "    \"EUR\",\n" +
            "    \"FJD\",\n" +
            "    \"FKP\",\n" +
            "    \"GBP\",\n" +
            "    \"GEL\",\n" +
            "    \"GGP\",\n" +
            "    \"GHS\",\n" +
            "    \"GIP\",\n" +
            "    \"GMD\",\n" +
            "    \"GNF\",\n" +
            "    \"GTQ\",\n" +
            "    \"GYD\",\n" +
            "    \"HKD\",\n" +
            "    \"HNL\",\n" +
            "    \"HRK\",\n" +
            "    \"HTG\",\n" +
            "    \"HUF\",\n" +
            "    \"IDR\",\n" +
            "    \"ILS\",\n" +
            "    \"IMP\",\n" +
            "    \"INR\",\n" +
            "    \"IQD\",\n" +
            "    \"IRR\",\n" +
            "    \"ISK\",\n" +
            "    \"JEP\",\n" +
            "    \"JMD\",\n" +
            "    \"JOD\",\n" +
            "    \"JPY\",\n" +
            "    \"KES\",\n" +
            "    \"KGS\",\n" +
            "    \"KHR\",\n" +
            "    \"KMF\",\n" +
            "    \"KPW\",\n" +
            "    \"KRW\",\n" +
            "    \"KWD\",\n" +
            "    \"KYD\",\n" +
            "    \"KZT\",\n" +
            "    \"LAK\",\n" +
            "    \"LBP\",\n" +
            "    \"LKR\",\n" +
            "    \"LRD\",\n" +
            "    \"LSL\",\n" +
            "    \"LTL\",\n" +
            "    \"LVL\",\n" +
            "    \"LYD\",\n" +
            "    \"MAD\",\n" +
            "    \"MDL\",\n" +
            "    \"MGA\",\n" +
            "    \"MKD\",\n" +
            "    \"MMK\",\n" +
            "    \"MNT\",\n" +
            "    \"MOP\",\n" +
            "    \"MRO\",\n" +
            "    \"MUR\",\n" +
            "    \"MVR\",\n" +
            "    \"MWK\",\n" +
            "    \"MXN\",\n" +
            "    \"MYR\",\n" +
            "    \"MZN\",\n" +
            "    \"NAD\",\n" +
            "    \"NGN\",\n" +
            "    \"NIO\",\n" +
            "    \"NOK\",\n" +
            "    \"NPR\",\n" +
            "    \"NZD\",\n" +
            "    \"OMR\",\n" +
            "    \"PAB\",\n" +
            "    \"PEN\",\n" +
            "    \"PGK\",\n" +
            "    \"PHP\",\n" +
            "    \"PKR\",\n" +
            "    \"PLN\",\n" +
            "    \"PYG\",\n" +
            "    \"QAR\",\n" +
            "    \"RON\",\n" +
            "    \"RSD\",\n" +
            "    \"RUB\",\n" +
            "    \"RWF\",\n" +
            "    \"SAR\",\n" +
            "    \"SBD\",\n" +
            "    \"SCR\",\n" +
            "    \"SDG\",\n" +
            "    \"SEK\",\n" +
            "    \"SGD\",\n" +
            "    \"SHP\",\n" +
            "    \"SLL\",\n" +
            "    \"SOS\",\n" +
            "    \"SRD\",\n" +
            "    \"STD\",\n" +
            "    \"SVC\",\n" +
            "    \"SYP\",\n" +
            "    \"SZL\",\n" +
            "    \"THB\",\n" +
            "    \"TJS\",\n" +
            "    \"TMT\",\n" +
            "    \"TND\",\n" +
            "    \"TOP\",\n" +
            "    \"TRY\",\n" +
            "    \"TTD\",\n" +
            "    \"TWD\",\n" +
            "    \"TZS\",\n" +
            "    \"UAH\",\n" +
            "    \"UGX\",\n" +
            "    \"USD\",\n" +
            "    \"UYU\",\n" +
            "    \"UZS\",\n" +
            "    \"VEF\",\n" +
            "    \"VND\",\n" +
            "    \"VUV\",\n" +
            "    \"WST\",\n" +
            "    \"XAF\",\n" +
            "    \"XAG\",\n" +
            "    \"XAU\",\n" +
            "    \"XCD\",\n" +
            "    \"XDR\",\n" +
            "    \"XOF\",\n" +
            "    \"XPF\",\n" +
            "    \"YER\",\n" +
            "    \"ZAR\",\n" +
            "    \"ZMK\",\n" +
            "    \"ZMW\",\n" +
            "    \"ZWL\"\n" +
            "]\n" +
            "}"

    const val APP_LOADED_FIRST_TIME = "app_loaded_first_time"
    const val APP_SHARED_PREFERENCE_NAME = "exchange_app_pref"
    const val DATABASE_NAME = "exchange_app_db"
    const val EUR = "EUR"
}